#pragma once
#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define SPARKYSPARKY_VERSION_MAJOR 0
#define SPARKYSPARKY_VERSION_MINOR 1
#define SPARKYSPARKY_VERSION_PATCH 0

#ifndef SPARKYSPARKY_VERSION_GIT
#define SPARKYSPARKY_VERSION_GIT "undefined"
#endif

#define SPARKYSPARKY_VERSION             \
    TOSTRING(SPARKYSPARKY_VERSION_MAJOR) \
    "." TOSTRING(SPARKYSPARKY_VERSION_MINOR) "." TOSTRING(SPARKYSPARKY_VERSION_PATCH) "-" SPARKYSPARKY_VERSION_GIT
